### ISSUE TITLE
No 'target'/ 'release' / name found

### ISSUE THREAD

**Issue by Anikmoujegy** [elevenhsoft/WebApps#1]
install -Dm0755 ./target/release/cosmic-wam /usr/bin/cosmic-wam
install: cannot stat './target/release/cosmic-wam': No such file or directory
error: Recipe `install` failed on line 63 with exit code 1

**Comment by elevenhsoft** [comment]
Hey,
Just to make sure. Did you build it previously?

To install you should run both commands, so in order
`just`
`sudo just install`

First run will make an executable and second one will copy items to given directories.

**Comment by elevenhsoft** [comment]
btw. Pop OS packaging this app already in them repository: https://github.com/pop-os/cosmic-webapps

You can install it via apt, `sudo apt install cosmic-webapps`
