### ISSUE TITLE
Textboxes sticks to end of the text

### ISSUE THREAD

**Issue by Tahinli** [elevenhsoft/WebApps#16]
Hi, textboxes does not allow me to write something to the front of the text, if there is some characters in the box.

https://github.com/elevenhsoft/WebApps/assets/96421894/2ec96b92-a222-41f5-9264-312db9985fbb

**Comment by elevenhsoft** [comment]
Yeah. It's because we using `focus` command to fix this bug: #12 but as wee see it produces more bugs.
I must think how to deal with it. Probably I'm gonna redesign warning message a bit. Thank you.

**Comment by elevenhsoft** [comment]
Ok, I guess I fixed this with: https://github.com/elevenhsoft/WebApps/commit/8270a5c1ac7ae28e9b71eb903e8f7f29e7ca2546

**Comment by Tahinli** [comment]
Yes

**Comment by elevenhsoft** [comment]
Thanks!
