### ISSUE TITLE
Set a maximum width for contents of the window

### ISSUE THREAD

**Issue by mmstick** [elevenhsoft/WebApps#23]
On a large display with tiling enabled, the content area gets stretched far too wide. There should be a reasonable max width that is centered in the application.

**Comment by elevenhsoft** [comment]
Oh, yeah. Definitely. I did not test it properly on large display or large window size. Thank you!

**Comment by elevenhsoft** [comment]
Well, I was not sure proper value for max_width, so I choose 1000px, which should be fine. App does not look too stretched, also there is some place for icon selector. And the list looks good. I don't have super-wide monitor to test it on it, but window content is centered with max_width, ok, imho, should be fine ^^

Thank you!
