### ISSUE TITLE
Styling issues

### ISSUE THREAD

**Issue by mmstick** [elevenhsoft/WebApps#24]
- On the main page, applications are displayed with an insensitive button, which makes their text grayed out
    - This could be either an `inline_input()`, or an `editable_input()`
- The close and editing buttons are too wide. Maybe they should be positioned at the end of the layout.
    - Canceling isn't a destructive action, so it should be a standard button style
    - Perhaps the toggles should be in the same column, and buttons in the same column as well.

**Comment by elevenhsoft** [comment]
Hello, I made a commit with some changes. If you would like to see now, please give some feedback. Maybe I will keep this issue open for a while, and see if someone else will have some ideas :)

Thanks!

**Comment by elevenhsoft** [comment]
> * This could be either an `inline_input()`, or an `editable_input()`

This one, especially `editable_input()` make me wish to make possible to edit web app title directly from home_screen. And you know what? Tomorrow it will be possible ^^
