### ISSUE TITLE
Crash When Try to Edit

### ISSUE THREAD

**Issue by Tahinli** [elevenhsoft/WebApps#25]
Hi, Flatpak version crashes when i want to edit  a web app.

https://github.com/elevenhsoft/WebApps/assets/96421894/5a33284b-91bf-4b39-ba68-7cf551509e5b

**Comment by elevenhsoft** [comment]
Oh yeah. It's panic while moving icon from one location to destination. I must protect it to no crash, but might be some problems with app icon then. However it's better than crash. 

We support 2 options, system-wide and flatpak installation. It's kind of mess since as flatpak we don't have access to full system and we stores some files in sandbox location. Creating an web app in one option, and then running flatpak version for example produces some errors :/

**Comment by elevenhsoft** [comment]
@Tahinli I just realized you are using previous version. Yesterday I pushed new release on flathub. Could you please test if issue still exists? From what I see, your panic is basing on previous code, i made changes in this line later.

**Comment by Tahinli** [comment]
> @Tahinli I just realized you are using previous version. Yesterday I pushed new release on flathub. Could you please test if issue still exists? From what I see, your panic is basing on previous code, i made changes in this line later.

Are you sure ?, I think I'm upstream

![image](https://github.com/elevenhsoft/WebApps/assets/96421894/7a5dc697-79dc-45b3-93cf-260e22c369a0)

**Comment by elevenhsoft** [comment]
Oh yeah in that case you are right. I just checked line what panic messages said and it was totally different. Tomorrow im gonna investigate it. However im pretty sure now it should not panic since latest changes on this space. We will test it.

**Comment by Tahinli** [comment]
> Oh yeah in that case you are right. I just checked line what panic messages said and it was totally different. Tomorrow im gonna investigate it. However im pretty sure now it should not panic since latest changes on this space. We will test it.

I'm not sure but is there a chance to break flatpak version when we compile from source and use ? Because while trying to commit into the project, I did it.

**Comment by elevenhsoft** [comment]
No. You don't break anything. Flatpak is sandboxed so it's not inferer each other. But I see your problem

Current situation is that, we can't use web apps created in one version, on another. The paths for icons, are different so it will crash like this. Meanwhile, just got an idea to hide, let's say "broken" launcher, so people won't be able to edit and see them, but in the same time, they will be crash free. Of course those launcher will be still visible in system docks, launchers, app menu, etc. The only thing is that, they won't be displayed in COSMIC Web Apps, but they won't work in app also. So I think it's a reasonable solution for now.

**Comment by Tahinli** [comment]
> No. You don't break anything. Flatpak is sandboxed so it's not inferer each other. But I see your problem
> 
> Current situation is that, we can't use web apps created in one version, on another. The paths for icons, are different so it will crash like this. Meanwhile, just got an idea to hide, let's say "broken" launcher, so people won't be able to edit and see them, but in the same time, they will be crash free. Of course those launcher will be still visible in system docks, launchers, app menu, etc. The only thing is that, they won't be displayed in COSMIC Web Apps, but they won't work in app also. So I think it's a reasonable solution for now.

It doesn't feel right. There should be a better way than hiding.

**Comment by elevenhsoft** [comment]
We can also ask for flatpak permission to ~/.local/share/icons with `rw` and store icons there. It will be available in flatpak and non-flatpak versions. Then it should not be issues at all. If I remember correctly. This is the only thing which makes them incompatible with each other. Oh. Browsers profiles too. And I wanted to keep permissions to minimal. I'm not sure yet what we will do with it. Today is kinda late for me to thinking^^

**Comment by elevenhsoft** [comment]
Hey @Tahinli 

I made some changes. Now web apps created with one version of COSMIC Web Apps will be compatible with the other, please read: https://github.com/elevenhsoft/WebApps?tab=readme-ov-file#breaking-change--042

**Comment by elevenhsoft** [comment]
I think we can close it. Imho it's resolved. The problem was definitely with incompatibility system-wide/flatpak installation.

**Comment by Tahinli** [comment]
I have an idea, I hope this may help. Instead of directly request for permission, we can spawn a file picker so user select a folder to store configs and profiles. This may help to prevent standard user from arguing with flatpak permission.

**Comment by elevenhsoft** [comment]
It won't help. We need sandbox permission for user directory. Otherwise we will struggle with those crashes again.
Now we have centralized locations, and both versions use the same. So launchers won't make a crash. This is ideal solution but....

Flatpak browsers does not see our directory. We need to manualy add permission for them. If user will pick via file picker location. Still. He will see only sandboxed locations because sandbox won't allow him to look further.

**Comment by elevenhsoft** [comment]
I think there is no golden middle. For now we was fighting with flatpak sandbox. There must be a compromise.

Current situation is not that bad. User will allow only once browser to look into our directory. Unfortunately he will have to do it for all browsers what he want to use. Thats a minus.

I would recommend using `just` method. Since it's more convenient but flathub installation is faster. 

Hard decisions ^^

**Comment by Tahinli** [comment]
If the problem only happens when a user uses both system wide and flatpak version ignore it. If the bug happens after every flatpak update then we need to fix. This makes me confused, I couldn't understand which one is our problem precisely.

**Comment by elevenhsoft** [comment]
Nah. It's only problem for both versions. We could ignore but always can someone come to report not working launcher. I wanted to hide it but you were right. It's not the best solution.

Let's see what will happen now. If people will be angry. Well. I will have to think harder ^^

**Comment by elevenhsoft** [comment]
btw. Chromium browsers are not affected i think. Tested with vivaldi and ungoogled chromium. Works out of the box.

Only firefox and forks require manual intervention. Not that bad.

**Comment by Tahinli** [comment]
> Nah. It's only problem for both versions. We could ignore but always can someone come to report not working launcher. I wanted to hide it but you were right. It's not the best solution.
> 
> Let's see what will happen now. If people will be angry. Well. I will have to think harder ^^

Until this app be included in major distros repos, many people will use flatpak. Because of this  I think we should satisfy them first.

My suggestion is: until we find a better a way, keep this issue open, and revert the last changes about flatpak permission.

**Comment by elevenhsoft** [comment]
Well. I'm not sure yet. Tomorrow I will do more tests but I think we can keep profiles in their sandboxed dirs. To be honest. Only icons did a crash, not profiles. Profiles are read in desktop file. Launcher does not need to see it while creating or edit. Only browser need to see the path. 

If I'm thinking about it more. I guess I was wrong with this decisions. Not the first and probably not the last time when I was wrong hahah. Like I said. Tomorrow I will do more tests. Maybe fix will come soon, so I will push it to flathub.

The pros is that, now we can easy clean directories while deleting entry. But in current app architecture it should be easy anyway, so this change makes less sense.

About profiles, probably I will revert this change. Well, i introduced much chaos today haha

**Comment by Tahinli** [comment]
> Well. I'm not sure yet. Tomorrow I will do more tests but I think we can keep profiles in their sandboxed dirs. To be honest. Only icons did a crash, not profiles. Profiles are read in desktop file. COSMIC Web Apps does not need to see it while creating or edit. Only browser need to see the path.
> 
> If I'm thinking about it more. I guess I was wrong with this decisions. Not the first and probably not the last time when I was wrong hahah. Like I said. Tomorrow I will do more tests. Maybe fix will come soon, so I will push it to flathub.
> 
> The pros is that, now we can easy clean directories while deleting entry. But in current app architecture it should be easy anyway, so this change makes less sense.
> 
> About profiles, probably I will revert this change. Well, i introduced much chaos today haha

No problem, you're just trying to do right things.

**Comment by elevenhsoft** [comment]
Yes. And knowing me, im working like crazy haha Making decisions too fast ;p

**Comment by elevenhsoft** [comment]
Ok, I solved it. Finally I think I found golden middle haha. Currenly in process on pushing to flathub. It can take few hours to update since we changed permissions, so they have to approve this change, but updated version should be bug free.

**Comment by Tahinli** [comment]
Flatpak finally updated, and working like a charm.

**Comment by elevenhsoft** [comment]
Wooho! :partying_face: we did it ^^ thank you, my friend for testing :)
