### ISSUE TITLE
Some Flatpak browsers are not visible

### ISSUE THREAD

**Issue by botus99** [elevenhsoft/WebApps#26]
## Description:
When creating a new Web App, the 'Select Browser' option only shows one of my Flatpak installed browsers (LibreWolf), but not Ungoogled Chromium or Floorp, which I also have installed through Flatpak.

## Steps to Reproduce:
1. Create new Web App
2. Attempt to select a browser other than LibreWolf
3. ???

## Expected Behavior:
Ability to select other Flatpak installed web browsers

## Actual Behavior:
Ability to select LibreWolf and only LibreWolf

## Environment:
- **Operating System:** Debian Testing
- **WebApps Version:** v0.4.1

## Additional Context:
I have updated my Debian system and also updated all Flatpaks as of this morning. The issue was there both before and after doing any upgrades.

Thank you for your hard work!

**Comment by elevenhsoft** [comment]
Hey, sorry for late response. Im kind of busy. Cant test it right now but tomorrow i will take a look. Thank you for nice report!

**Comment by elevenhsoft** [comment]
Hello again,

Just added those browsers: https://github.com/elevenhsoft/WebApps/commit/62c2b65c671acc98085b152f8cac5633d076af26
You can test it from master or wait for a flatpak update. I'm not sure. Maybe today, maybe tomorrow. I'm pushing flathub often, don't want make them angry ^^

**Comment by botus99** [comment]
Haha thanks for the quick response! 7hrs after your post (aka now) I ran 'flatpak update' and it looks like they still need some more time. The UC path fix and Floorp addition look like you got this issue knocked out though :trophy: 

Much appreciated and good job with the rapid development of an awesome app!

**Comment by elevenhsoft** [comment]
It's updated already. Please read readme. About this issue in README, I can say probably I found a solution. But changes will come as soon as possible.
