### ISSUE TITLE
Icon list is shown on wrong screen.

### ISSUE THREAD

**Issue by FlorianLudwig** [elevenhsoft/WebApps#30]
# Issue

Icon list is shown on wrong screen.

## Steps to reproduce

1. edit web app
2. click the icon
3. search some icon, press enter
4. wait until list of icons is displayed
5. click home button to go back to web app list
6. click edit again
7. click on browser name

(there are other ways to come to the same result)

## Result

The drop-down to select a browser and the previous icon search at the same time:

![image](https://github.com/elevenhsoft/WebApps/assets/432263/824cd434-e550-4c0b-8391-af7d03ccbca1)

**Comment by elevenhsoft** [comment]
Hello, thank you for your report!

Is it reproducible every time? I tried and it won't happen. I remember once I had this issue but could not reproduce it anymore. I wonder if it's my fault and layout related issue (or pages in this example) or libcosmic on different desktops. 

I'm gonna test soon on different desktops to see how it works (or not^^)

**Comment by elevenhsoft** [comment]
I think it's fixed upstream. Just updated dependencies and from my tests looks like it should works without this weird overflow anymore. Thank you!
