### ISSUE TITLE
[Bug] Copy URL and paste make app hang

### ISSUE THREAD

**Issue by ZorinFoss** [elevenhsoft/WebApps#33]
Hi,

When i try to copy URL link and paste it while i create new app, The app hang and does not respond.

i hope this will fix soon.

Thanks,

**Comment by elevenhsoft** [comment]
Hey, it's duplicate: https://github.com/elevenhsoft/WebApps/issues/11

This is known issue in libcosmic. For now, we can't fix it in app i guess. We should wait for upstream fix, which probably will come soon, since many apps based on libcosmic are affected.
