### ISSUE TITLE
freezes when pasting url into url field

### ISSUE THREAD

**Issue by BBBalls** [elevenhsoft/WebApps#36]
When trying to create a new PWA, COSMIC Web Apps freezes when pasting url into url field.

Using the Flatpak of COSMIC Web Apps on POP!_OS 22.04 in a Wayland session of the Gnome based DE.

**Comment by elevenhsoft** [comment]
Hey, so sorry for late response. It's a known issue upstream: https://github.com/elevenhsoft/WebApps/issues/11

We should wait for fix. Few libcosmic apps have this problem. I'm not sure if it's fixed. Soon, i will update dependencies to newer revisions. Currently I don't know workaround for this and i don't know how to prevent this. Just don't paste :/
