### ISSUE TITLE
Nix browsers

### ISSUE THREAD

**Issue by kcalvelli** [elevenhsoft/WebApps#38]
I wanted to use this on Nixos, so I created a fork which added a number of popular browsers on Nix.  I accidentally submitted a PR to you earlier but closed it.  Happy to contribute if you are interested at all.  

https://github.com/kcalvelli/WebApps/tree/nix_browsers

I also built a nix derivation which works, so happy to share that as well if you are interested.

**Comment by elevenhsoft** [comment]
Hello! Thanks for your interest :)

Looking into your commits it should not break anything but adding something new. If you want we can merge this. Also, if you are able to prepare nix packaging, would be awesome. I had some requests for this, but unfortunately I'm complete noob in Nix. Used this OS once and never settled on it ^^

**Comment by kcalvelli** [comment]
Great!  Submitted PR.

I'll test my nix packaging some more as I am also pretty noobish with writing derivations.  Will ask some folks who know what they are doing to take a look at what I have.

**Comment by elevenhsoft** [comment]
Thank you and no worries :)
