### ISSUE TITLE
Any plans to package it as a flatpak?

### ISSUE THREAD

**Issue by jcmolinajr** [elevenhsoft/WebApps#4]
First of all. Excellent work! Any plans to package it as a flatpak?

**Comment by elevenhsoft** [comment]
Hey. Thank you. Yes. Im currently on process to adding it to flathub. There were some problems. Tomorrow i will upload new manifest and we will wait :)

**Comment by elevenhsoft** [comment]
PR merged, so now we have new repo on flathub: https://github.com/flathub/io.github.elevenhsoft.WebApps

The page for this app is: https://flathub.org/apps/io.github.elevenhsoft.WebApps

So we can close :) Cheers
