### ISSUE TITLE
Feature Request: Icon Theme

### ISSUE THREAD

**Issue by rrahl0** [elevenhsoft/WebApps#40]
Hey, I am the packager for openSUSE COSMIC, and wanted to ask if it would be possible, to add a (buildtime) flag for disabling downloading the icon theme. I want to provide the icons as a requirement through the normal rpm package, so not every user has to download the same icon pack over and over.

**Comment by elevenhsoft** [comment]
First of all, thanks for packaging! COSMIC need to spread over the Linux world^^

About the issue. Well. I must consider this but lately I'm kind of busy. It's definitely something we can do, but let me think how to solve this :) The icons should not be downloaded, when found Papirus theme in ~/.local/share/icons.
Installing icons system-wide via rpm, installs them in `/usr/share/icons`, right? If so, then it won't be found by COSMIC Web Apps. We probably could change it, to look into `/usr/share/icons` directory also.

**Comment by rrahl0** [comment]
Yes, system icons are in /usr/share/icons. And please take your time :). We are still pre alpha stage (the whole ecosystem).

**Comment by elevenhsoft** [comment]
Well, if we support `/usr/share/icons` location, then probably we don't need to download additional icons pack. One will be always available. Maybe just move downloader to icon selector, and add a button there which will be visible only when icon pack won't be installed.

**Comment by elevenhsoft** [comment]
Ok, so just added support for system paths: https://github.com/elevenhsoft/WebApps/commit/696e885a1727da77ac81e944b873081da942247b 
Also made a button to manually trigger Papirus installer, but only when it does not find Papirus icon theme: https://github.com/elevenhsoft/WebApps/commit/dbe57271f5c07b5754e3a42f50e685a2f53202d5

Please take a look, and give me some feedback. Thanks!

**Comment by rrahl0** [comment]
Thank you very much. my first few tests were working perfectly :+1:
