### ISSUE TITLE
[Feature] Add these browser to the browsers list

### ISSUE THREAD

**Issue by ZorinFoss** [elevenhsoft/WebApps#45]
Hi,

Please add these browsers to to the browsers list. (These browser does not shown while chosen a browser)
- Chromium
- Cromite
- Thorium

**P.S:** I use `WebApps` installed from **arch linux aur** not flatpak. Only browsers detected is `chrome` and `brave`

Thanks,

**Comment by elevenhsoft** [comment]
Hello,

Chromium is there: https://github.com/elevenhsoft/WebApps/blob/master/src/supported_browsers.rs#L62-L82, but why it's not recognized for you I'm not sure. How you installed this browser?




> * Cromite
> 
> * Thorium

Added those: https://github.com/elevenhsoft/WebApps/commit/16c058e92ddb9dab06f2548ff137615f4cf3d755
I can't test it so please give me some feedback. I hope it will works for you.

**Comment by ZorinFoss** [comment]
Thank you, All browser i mentioned above are recognized and works fine.
