### ISSUE TITLE
Icon not loading

### ISSUE THREAD

**Issue by BhJaipal** [elevenhsoft/WebApps#52]
Icons are not loading
On selecting PNG Icon from files, nothing happens
On selecting SVG Icon from files, app closes with error

```
called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by elevenhsoft** [comment]
Flatpak?

**Comment by BhJaipal** [comment]
Yes, now I am trying to clone repo and install it

**Comment by BhJaipal** [comment]
jaipal001@pop-os:~$ cd CosmicWebApps/
jaipal001@pop-os:~/CosmicWebApps$ just
cargo build --release
    Updating crates.io index
    Updating git repository `https://github.com/gfx-rs/wgpu`
error: failed to get `wgpu` as a dependency of package `iced_wgpu v0.12.0 (https://github.com/pop-os/libcosmic#c9f8f485)`
    ... which satisfies git dependency `iced_wgpu` (locked to 0.12.0) of package `libcosmic v0.1.0 (https://github.com/pop-os/libcosmic#c9f8f485)`
    ... which satisfies git dependency `libcosmic` (locked to 0.1.0) of package `webapps v0.4.6 (/home/jaipal001/CosmicWebApps)`

Caused by:
  failed to load source for dependency `wgpu`

Caused by:
  Unable to update https://github.com/gfx-rs/wgpu?rev=20fda69#20fda698

Caused by:
  failed to fetch into: /home/jaipal001/.cargo/git/db/wgpu-53e70f8674b08dd4

Caused by:
  network failure seems to have happened
  if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  SSL error: unknown error; class=Ssl (16)
error: Recipe `build-debug` failed on line 32 with exit code 101

**Comment by elevenhsoft** [comment]
About flatpak. It looks like you don't have permission for icons directories. Did you modify them before? If it set as default, it should works.

The second issue with compilation is while fetching dependencies. Maybe some network issues?

**Comment by BhJaipal** [comment]
> About flatpak. It looks like you don't have permission for icons directories. Did you modify them before? If it set as default, it should works.
> 
> The second issue with compilation is while fetching dependencies. Maybe some network issues?

.icons folder?
I have icons in them, do I have to remove them?

**Comment by elevenhsoft** [comment]
> > About flatpak. It looks like you don't have permission for icons directories. Did you modify them before? If it set as default, it should works.
> > The second issue with compilation is while fetching dependencies. Maybe some network issues?
> 
> .icons folder? I have icons in them, do I have to remove them?

No, no. No .icons in your home directory. We need permission for this location: https://github.com/elevenhsoft/WebApps/blob/master/src/common.rs#L68-L70

~/.local/share/icons.

They are set by default for flatpak. I was guessing you changed something, so that's why you got permission denied.

**Comment by BhJaipal** [comment]
> > > About flatpak. It looks like you don't have permission for icons directories. Did you modify them before? If it set as default, it should works.
> > > The second issue with compilation is while fetching dependencies. Maybe some network issues?
> > 
> > .icons folder? I have icons in them, do I have to remove them?
> 
> No, no. No .icons in your home directory. We need permission for this location: https://github.com/elevenhsoft/WebApps/blob/master/src/common.rs#L68-L70
> 
> ~/.local/share/icons.
> 
> They are set by default for flatpak. I was guessing you changed something, so that's why you got permission denied.
> 
> Maybe you don't have created this directory. I'm not sure if we are creating it, in case it's not exist. 

Ok, what I change the permissions to?

**Comment by BhJaipal** [comment]
> > > About flatpak. It looks like you don't have permission for icons directories. Did you modify them before? If it set as default, it should works.
> > > The second issue with compilation is while fetching dependencies. Maybe some network issues?
> > 
> > .icons folder? I have icons in them, do I have to remove them?
> 
> No, no. No .icons in your home directory. We need permission for this location: https://github.com/elevenhsoft/WebApps/blob/master/src/common.rs#L68-L70
> 
> ~/.local/share/icons.
> 
> They are set by default for flatpak. I was guessing you changed something, so that's why you got permission denied.
> 
> Maybe you don't have created this directory. I'm not sure if we are creating it, in case it's not exist. 

Because of this icons problem, I am now trying to create my own app in flutter now😂, using sqlite db
